In [1]:
import pandas as pd

hourly_df = pd.read_csv(
    "../data/processed/hourly_energy.csv"
)

hourly_df["x_Timestamp"] = pd.to_datetime(
    hourly_df["x_Timestamp"]
)

In [2]:
grid_df = (
    hourly_df
    .groupby("x_Timestamp")
    ["t_kWh"]
    .sum()
    .reset_index()
)

grid_df.head()

          x_Timestamp   t_kWh
0 2019-05-01 00:00:00  14.472
1 2019-05-01 01:00:00  13.408
2 2019-05-01 02:00:00  12.473
3 2019-05-01 03:00:00  11.334
4 2019-05-01 04:00:00  10.468

In [3]:
grid_df.shape

(21960, 2)

In [4]:
grid_df["hour"] = grid_df["x_Timestamp"].dt.hour
grid_df["dayofweek"] = grid_df["x_Timestamp"].dt.dayofweek
grid_df["month"] = grid_df["x_Timestamp"].dt.month

In [5]:
grid_df["lag_1"] = grid_df["t_kWh"].shift(1)
grid_df["lag_24"] = grid_df["t_kWh"].shift(24)
grid_df["lag_168"] = grid_df["t_kWh"].shift(168)

In [6]:
grid_df["rolling_mean_24"] = (
    grid_df["t_kWh"]
    .rolling(24)
    .mean()
)

grid_df["rolling_std_24"] = (
    grid_df["t_kWh"]
    .rolling(24)
    .std()
)

In [7]:
grid_df = grid_df.dropna()

In [8]:
grid_df.to_csv(
    "../data/processed/grid_energy.csv",
    index=False
)

In [9]:
grid_df.shape
grid_df.head()

,x_Timestamp,t_kWh,hour,dayofweek,month,lag_1,lag_24,lag_168,rolling_mean_24,rolling_std_24
168,2019-05-08 00:00:00,14.549,0,2,5,15.254,15.761,14.472,8.304625,3.768903
169,2019-05-08 01:00:00,14.295,1,2,5,14.549,13.762,13.408,8.326833,3.803867
170,2019-05-08 02:00:00,12.692,2,2,5,14.295,12.359,12.473,8.340708,3.819788
171,2019-05-08 03:00:00,11.272,3,2,5,12.692,11.143,11.334,8.346083,3.823992
172,2019-05-08 04:00:00,9.802,4,2,5,11.272,10.817,10.468,8.303792,3.801020